server.port: 8084
Amount: 10000
Term: 6
general-rate: 8
increasing-without-insurance: 3
increasing-not-salary-client: 1
sum-insurance: 10000
spring.jpa.hibernate.ddl-auto: update
spring.jpa.hibernate.show_sql: true
spring.datasource:
  url: 'jdbc:postgresql://postgresql:5432/dealDb'
  username: postgres
  password: postgres
  driver-class:
    jdbc:
      driver: org.postgresql.Driver
Conveyor:
  url: 'http://ms-request-credit:8083'
spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER